version: '3.9'

services:
  web:
    image: nginxphp
    build: .
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - $DATA_DIR:/app/public
      - logs-web:/var/log/nginx
    depends_on:
      - database
    restart: unless-stopped
    environment:
      - PUID=$PUID
      - PGID=$PUID
      - TIMEZONE=$TIMEZONE
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.php.entrypoints=web,websecure"
      - "traefik.http.routers.php.rule=Host(`${PHP_PREFIX:-php}.${DOMAIN}`)"
      - "traefik.http.services.php.loadbalancer.server.port=80"
      - "traefik.http.routers.php.tls=true"
      - "traefik.http.routers.php.tls.certresolver=leresolver"
    networks:
      - lan
      - traefik_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8280:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - database
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.phpmyadmin.entrypoints=web,websecure"
      - "traefik.http.routers.phpmyadmin.rule=Host(`${PHPMYADMIN_PREFIX:-phpmyadmin}.${DOMAIN}`)"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
      - "traefik.http.routers.phpmyadmin.tls=true"
      - "traefik.http.routers.phpmyadmin.tls.certresolver=leresolver"
    networks:
      - lan
      - traefik_network

  database:
    image: mariadb
    container_name: php_database
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME:-php}
      - MYSQL_USER=${DB_USER:-php}
      - MYSQL_PASSWORD=${DB_PASS}
      - PUID=$PUID
      - PGID=$PUID
      - TZ=$TIMEZONE
    networks:
      - lan
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3


volumes:
  logs-php-fpm:
  logs-web:
  db:

networks:
  lan:
  traefik_network:
    external: true
